#---------------------------------------------
# nextcloud configuration without proxy
#---------------------------------------------
# $ cp sample.env .env  # create configuration
# $ ./gen-password      # create strong password
# $ nano .env           # edit config vars
#---------------------------------------------
# adapted from https://github.com/nextcloud/docker
#---------------------------------------------

version: '3'

services:

  db:
    container_name: ${MYSQL_CONTAINER:-nextcloud-mariadb}
    build: ${MYSQL_IMAGE:-./images/mariadb}
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: unless-stopped
    volumes:
      - ${DIR_DATA_MARIADB:-./data/mariadb}/db:/var/lib/mysql
      - ${DIR_DATA_MARIADB:-./data/mariadb}/etc:/etc/mysql
      - ${DIR_DATA_MARIADB:-./data/mariadb}/init:/database-init
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE:-nextcloud}
      - MYSQL_USER=${MYSQL_USER:-nextcloud}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-randomPassword}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-randomPassword}


  db_backup:
    container_name: ${DB_BACKUP_CONTAINER:-nextcloud-mariadb-backup}
    build: 
      context: ${DB_BACKUP_IMAGE:-./images/db-backup}
      args:
        - CRON_CMD=${DB_BACKUP_CRON_CMD:-0 5 * * 0}
    restart: unless-stopped
    depends_on:
      - db
    environment:
      - DB_BACKUP_HOST=${MYSQL_CONTAINER:-nextcloud-mariadb}
      - DB_BACKUP_NAME=${MYSQL_DATABASE:-nextcloud}
      - DB_BACKUP_PASSWORD=${MYSQL_ROOT_PASSWORD:-randomPassword}
    volumes:
      - ${DIR_DATA_BACKUP:-./data/backup}:/backup
      - ${DIR_DATA_MARIADB:-./data/mariadb}/init:/backup-latest


  app:
    container_name: ${NEXTCLOUD_CONTAINER:-nextcloud-app}
    build: 
      context: ${NEXTCLOUD_IMAGE:-./images/nextcloud}
    depends_on:
      - db
    restart: unless-stopped
    ports:
      - ${PORT_HTTP:-9080}:80
      - ${PORT_HTTPS:-9443}:443
    volumes:
      - ${DIR_CONFIG_NEXTCLOUD:-./data/nextcloud}/config:/var/www/html/config
      - ${DIR_DATA_NEXTCLOUD:-./data/nextcloud}/apps:/var/www/html/apps
      - ${DIR_DATA_NEXTCLOUD:-./data/nextcloud}/data:/var/www/html/data
    environment:
#      - NEXTCLOUD_ADMIN_USER=${NEXTCLOUD_ADMIN_USER:-nextcloud}
#      - NEXTCLOUD_ADMIN_PASSWORD=${NEXTCLOUD_ADMIN_PASSWORD:-nextcloud}
      - NEXTCLOUD_DATA_DIR=${NEXTCLOUD_DATA_DIR:-/var/www/html/data}
      - NEXTCLOUD_TABLE_PREFIX=${NEXTCLOUD_TABLE_PREFIX:-}
      - NEXTCLOUD_TRUSTED_DOMAINS=${NEXTCLOUD_TRUSTED_DOMAINS:-}
      - NEXTCLOUD_UPDATE=${NEXTCLOUD_UPDATE:-0}
      - MYSQL_DATABASE=${MYSQL_DATABASE:-nextcloud}
      - MYSQL_USER=${MYSQL_USER:-nextcloud}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-randomPassword}
      - MYSQL_HOST=${MYSQL_CONTAINER:-nextcloud-mariadb}
      - SMTP_HOST=${SMTP_HOST:-}
      - SMTP_SECURE=${SMTP_SECURE:-}
      - SMTP_PORT=${SMTP_PORT:-465}
      - SMTP_AUTHTYPE=${SMTP_AUTHTYPE:-LOGIN}
      - SMTP_NAME=${SMTP_NAME:-}
      - SMTP_PASSWORD=${SMTP_PASSWORD:-}
      - MAIL_FROM_ADDRESS=${MAIL_FROM_ADDRESS:-}
      - MAIL_DOMAIN=${MAIL_DOMAIN:-}
      - APACHE_DISABLE_REWRITE_IP=${APACHE_DISABLE_REWRITE_IP:-}
      - TRUSTED_PROXIES=${TRUSTED_PROXIES:-}
      - OVERWRITEHOST=${OVERWRITEHOST:-}
      - OVERWRITEPROTOCOL=${OVERWRITEPROTOCOL:-}
      - OVERWRITEWEBROOT=${OVERWRITEWEBROOT:-}
      - OVERWRITECONDADDR=${OVERWRITECONDADDR:-}
    networks:
      - proxy-tier
      - default
 
networks:
  proxy-tier:
