#!/usr/bin/bash

source ./.env
docker=${PATH_DOCKER_COMPOSE:-/usr/bin/docker-compose}

echo
echo "-------------------------------------"
echo " Start jc://nextcloud/"
echo "-------------------------------------"
echo
echo "Port http/https: ${PORT_HTTP:-default}/${PORT_HTTPS:-default}"
echo "Image Nextcloud: ${NEXTCLOUD_IMAGE:-default}"
echo "Image MariaDB:   ${MYSQL_IMAGE:-default}"
echo

docker-compose up -d
