#!/bin/bash

user=`whoami`
source=../.env
nc_container=${NEXTCLOUD_CONTAINER:-nextcloud-app}
config=$1

echo
echo "-------------------------------------"
echo " Start jc://cloud/maintain/"
echo " (by Christoph Kloth)"
echo "-------------------------------------"

if [ $user != "root" ]; then 
  echo
  echo "Please run as root!"
  exit 0
fi

#------------------------------------------

nc_exec() {
   echo "execute php /var/www/html/occ $1 $2 $3"
   docker exec -u www-data -it $nc_container php /var/www/html/occ $1 $2 $3
   }

nc_status() {
   echo "show status"
   #nc_exec -V
   nc_exec status
   }

nc_apps_list() {
   echo "List available NextCloud apps"
   nc_exec app:list
   }
   
nc_apps_install() {
   echo "Install NextCloud app: $0"
   nc_exec app:install $0
   nc_exec app:enable $0
   }
   
nc_files_cleanup() {
   # see https://docs.nextcloud.com/server/15/admin_manual/configuration_server/occ_command.html#file-operations-label
   echo "cleanup filecache"
   nc_exec files:cleanup
   }

nc_files_rescan() {
   # see https://docs.nextcloud.com/server/15/admin_manual/configuration_server/occ_command.html#file-operations-label
   echo "rescan filesystem"
   nc_exec files:scan --all
   }
   
nc_db_add_primarykeys() {
   # see https://docs.nextcloud.com/server/15/admin_manual/configuration_server/occ_command.html#file-operations-label
   echo "add missing primary keys"
   nc_exec db:add-missing-primary-keys
   }

nc_db_add_indices() {
   # see https://docs.nextcloud.com/server/15/admin_manual/configuration_server/occ_command.html#file-operations-label
   echo "add missing indices"
   nc_exec db:add-missing-indices
   }

nc_db_convert_bigint() {
   # see https://docs.nextcloud.com/server/15/admin_manual/configuration_server/occ_command.html#file-operations-label
   echo "convert to bigint"
   nc_exec maintenance:mode --on
   nc_exec db:convert-filecache-bigint --no-interaction
   nc_exec maintenance:mode --off
   }

nc_db_background() {
   echo "execute /var/www/html/cron.php"
   docker exec -u www-data -it $nc_container php /var/www/html/cron.php
   }

nc_config_set() {
   # see https://docs.nextcloud.com/server/15/admin_manual/configuration_server/occ_command.html#config-commands-label
   echo "set value in config-file"
   nc_exec config:system:set $0 $1 $2 $3
   }

nc_config_updater() {
  echo "try to update nextcloud"
  # nc_exec maintenance:mode --on
  nc_exec update:check
  nc_exec app:update --all
  nc_exec upgrade
  #nc_exec maintenance:mode --off
  }

#------------------------------------------

if [ ! $config ]; then
  echo
  echo "Press key - your options:"
  echo " 'q' - exit"
  echo " '0' - status"
  echo " '1' - list nextcloud apps [list]"
  echo " '2' - install known nextcloud app [install]"
  echo " '3' - rescan filesystem [rescan]"
  echo " '4' - cleanup filecache [cleanup]"
  echo " '5' - add missing indices [indices]"
  echo " '6' - add missing primary keys [primarykeys]"
  echo " '7' - convert columns to bigint if missing [bigint]"
  echo " '8' - run background tasks [background]"
  echo " '9' - try to update nextcloud ($NEXTCLOUD_IMAGE)"
  count=0
  while : ; do
    read -n 1 k <&1
    if [[ $k = q ]] ; then
       printf "\n... quitting the program.\n"
       exit 0
    elif [[ $k = 0 ]] ; then
       config="status"
       break
    elif [[ $k = 1 ]] ; then
       config="list"
       break
    elif [[ $k = 2 ]] ; then
       config="install"
       break
    elif [[ $k = 3 ]] ; then
       config="rescan"
       break
    elif [[ $k = 4 ]] ; then
       config="cleanup"
       break
    elif [[ $k = 5 ]] ; then
       config="indices"
       break
    elif [[ $k = 6 ]] ; then
       config="primarykeys"
       break
    elif [[ $k = 7 ]] ; then
       config="bigint"
       break
    elif [[ $k = 8 ]] ; then
       config="background"
       break
    elif [[ $k = 9 ]] ; then
       config="update"
       break
    else
       ((count=$count+1))
       printf "\nIterate for  times\n"
       echo "Press 'q' to exit"
    fi
  done
fi

echo

if [ $config == "list" ]; then
    nc_apps_list
elif [ $config == "status" ]; then
    nc_status
elif [ $config == "rescan" ]; then
    nc_files_rescan
elif [ $config == "cleanup" ]; then
    nc_files_cleanup
elif [ $config == "install" ]; then
    nc_apps_install
elif [ $config == "indices" ]; then
    nc_db_add_indices
elif [ $config == "primarykeys" ]; then
    nc_db_add_primarykeys
elif [ $config == "bigint" ]; then
    nc_db_convert_bigint
elif [ $config == "background" ]; then
    nc_db_background
elif [ $config == "update" ]; then
    nc_config_updater
else
    echo "unknown command: $0"
fi 

echo
echo "Done."
